enableGlobalCache: false
yarnPath: .yarn/releases/yarn-4.5.3.cjs
compressionLevel: mixed

supportedArchitectures:
  cpu:
    - x64
    - arm64
  os:
    - darwin
    - linux
    - win32

packageExtensions:
  "eslint-plugin-storybook@*":
    dependencies:
      typescript: 5.7.2
  "@storybook/react-vite@*":
    dependencies:
      typescript: 5.7.2
  "@storybook/addon-docs@*":
    dependencies:
      "@types/react": 18.3.17
  "@storybook/core@*":
    dependencies:
      storybook: 8.4.7
  "@chromatic-com/storybook@*":
    dependencies:
      react: 18.3.1


